spring:
  profiles:
    include: auth, location
  application:
    name: examples
  cache:
    type: ${CACHE_TYPE:redis}
  redis:
    host: ${REDIS_URI:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD}
    ssl: true
    timeout: 5m

server:
  port: ${SERVER_PORT:8080}

#Actuator
management:
  endpoint:
    health:
      probes.enabled: true
      show-components: always
      show-details: always
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true

#Feign
feign:
  client:
    refresh-enabled: true
  circuitbreaker:
    enabled: false
    alphanumeric-ids:
      enabled: false

logging:
  level:
    com.tmus.prel.example: debug