name: Versioning

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  AUXILIARY_BRANCH: aux-branch

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
      pull-requests: write
      repository-projects: write
      checks: write
      deployments: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Versioning
      run: |
        git config --global user.email "mallmann.edu@gmail.com"
        git config --global user.name "Eduardo Mallmann"
        git config --global push.followTags true
        git checkout -b ${{ env.AUXILIARY_BRANCH }}
        git push -u origin ${{ env.AUXILIARY_BRANCH }}
        mvn --batch-mode release:prepare
        NUMBER=$(curl --location --request POST '$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pulls' \
        --header 'Accept: Accept: application/vnd.github+json' \
        --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "title": "Versioning",
            "body": "Versioning PR",
            "head": "$GITHUB_REPOSITORY_OWNER:${{ env.AUXILIARY_BRANCH }}",
            "base": "main"
        }' | jq '.number')
        curl --location --request PUT '$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pulls/$NUMBER/merge' \
        --header 'Accept: application/vnd.github+json' \
        --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
        git push origin --delete ${{ env.AUXILIARY_BRANCH }}
