name: Versioning

on:
  pull_request:
    types:
      - closed

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Versioning
      run: |
        git config --global user.email "mallmann.edu@gmail.com"
        git config --global user.name "Eduardo Mallmann"
        git config --global push.followTags true
        mvn release:prepare