name: Versioning

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
      pull-requests: write
      repository-projects: write
      checks: write
      deployments: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      env:
        AUXILIARY_BRANCH: aux-branch
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Versioning
      run: |
        git config --global user.email "mallmann.edu@gmail.com"
        git config --global user.name "Eduardo Mallmann"
        git config --global push.followTags true
        mvn release:prepare
        git checkout -b ${{ AUXILIARY_BRANCH }}
        git push -u origin ${{ AUXILIARY_BRANCH }}
        curl --location --request POST 'https://api.github.com/repos/eduardomallmann/viacep-proxy/pulls' \
        --header 'Accept: Accept: application/vnd.github+json' \
        --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "title": "Versioning",
            "body": "Versioning PR",
            "head": "eduardomallmann:{{ $AUXILIARY_BRANCH }}",
            "base": "main"
        }'
        jq
